import 'package:flutter/material.dart';

abstract class Styles {
  static const ColorScheme lightScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff2d6a44),
    surfaceTint: Color(0xff2d6a44),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xffb1f1c2),
    onPrimaryContainer: Color(0xff00210e),
    secondary: Color(0xff4f6353),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xffd2e8d4),
    onSecondaryContainer: Color(0xff0d1f13),
    tertiary: Color(0xff8c4a60),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xffffd9e2),
    onTertiaryContainer: Color(0xff3a071d),
    error: Color(0xffba1a1a),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffffdad6),
    onErrorContainer: Color(0xff410002),
    surface: Color(0xfff6fbf3),
    onSurface: Color(0xff181d18),
    onSurfaceVariant: Color(0xff414942),
    outline: Color(0xff717971),
    outlineVariant: Color(0xffc0c9bf),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff2c322d),
    inversePrimary: Color(0xff95d5a7),
    primaryFixed: Color(0xffb1f1c2),
    onPrimaryFixed: Color(0xff00210e),
    primaryFixedDim: Color(0xff95d5a7),
    onPrimaryFixedVariant: Color(0xff10512e),
    secondaryFixed: Color(0xffd2e8d4),
    onSecondaryFixed: Color(0xff0d1f13),
    secondaryFixedDim: Color(0xffb6ccb9),
    onSecondaryFixedVariant: Color(0xff384b3d),
    tertiaryFixed: Color(0xffffd9e2),
    onTertiaryFixed: Color(0xff3a071d),
    tertiaryFixedDim: Color(0xffffb1c8),
    onTertiaryFixedVariant: Color(0xff703348),
    surfaceDim: Color(0xffd6dbd4),
    surfaceBright: Color(0xfff6fbf3),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfff0f5ed),
    surfaceContainer: Color(0xffeaefe8),
    surfaceContainerHigh: Color(0xffe5eae2),
    surfaceContainerHighest: Color(0xffdfe4dd),
  );

  static const ColorScheme darkScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff0a4d2b),
    surfaceTint: Color(0xff2d6a44),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xff448159),
    onPrimaryContainer: Color(0xffffffff),
    secondary: Color(0xff344739),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xff657a69),
    onSecondaryContainer: Color(0xffffffff),
    tertiary: Color(0xff6b2f45),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xffa55f76),
    onTertiaryContainer: Color(0xffffffff),
    error: Color(0xff8c0009),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffda342e),
    onErrorContainer: Color(0xffffffff),
    surface: Color(0xfff6fbf3),
    onSurface: Color(0xff181d18),
    onSurfaceVariant: Color(0xff3d453e),
    outline: Color(0xff59615a),
    outlineVariant: Color(0xff757d75),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff2c322d),
    inversePrimary: Color(0xff95d5a7),
    primaryFixed: Color(0xff448159),
    onPrimaryFixed: Color(0xffffffff),
    primaryFixedDim: Color(0xff2b6742),
    onPrimaryFixedVariant: Color(0xffffffff),
    secondaryFixed: Color(0xff657a69),
    onSecondaryFixed: Color(0xffffffff),
    secondaryFixedDim: Color(0xff4d6151),
    onSecondaryFixedVariant: Color(0xffffffff),
    tertiaryFixed: Color(0xffa55f76),
    onTertiaryFixed: Color(0xffffffff),
    tertiaryFixedDim: Color(0xff89475e),
    onTertiaryFixedVariant: Color(0xffffffff),
    surfaceDim: Color(0xffd6dbd4),
    surfaceBright: Color(0xfff6fbf3),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfff0f5ed),
    surfaceContainer: Color(0xffeaefe8),
    surfaceContainerHigh: Color(0xffe5eae2),
    surfaceContainerHighest: Color(0xffdfe4dd),
  );

  static const TextStyle dileveryTime = TextStyle(
    color: Color.fromRGBO(0, 0, 0, 0.8),
    fontSize: 18,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.normal,
  );

  static const TextStyle productRowTotal = TextStyle(
    color: Color.fromRGBO(0, 0, 0, 0.8),
    fontSize: 18,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.normal,
  );
}
